config:
  - synora/configs/**

# Add 'environment' to any changes to environment files
environment:
  - synora/envs/**

trainer:
  - synora/training/**

controller:
  - synora/controller/**

helpers:
  - synora/helpers/**

tokenizers:
  - synora/vision/video_tokenizer.py
  - synora/vision/vq_layer.py

tests:
  - tests/**
  - synora/testing/**

models:
  - synora/models/**

memory:
  - synora/memory/**

masks:
  - synora/masks/**

reward_functions:
  - synora/reward/**

observation_wrappers:
  - synora/observations/**

utilities:
  - synora/utils/**

vision:
  - synora/vision/**

transforms:
  - synora/transforms/**

# Add 'CI/CD' to any changes to GitHub workflows and automation config
CI/CD:
  - .github/workflows/**
  - .github/*.yml

# Add 'documentation' to any changes to documentation files
documentation:
  - README.md
  - CITATION.cff
  - LICENSE
  - docs/**
