"""Typing stub for the friendly ``synora`` public package.

Generated by ``python -m tools.gen_type_stub`` - do not edit by hand.

``synora`` resolves its public surface lazily at runtime, so every export has
to be spelled out here for type checkers and autocomplete to see it.
"""

from typing import Any

from synora import api as api

from synora.api import ENV_BACKEND_SPECS as ENV_BACKEND_SPECS
from synora.api import EnvBackendSpec as EnvBackendSpec
from synora.api import MODEL_SPECS as MODEL_SPECS
from synora.api import ModelSpec as ModelSpec
from synora.api import create_config as create_config
from synora.api import create_model as create_model
from synora.api import get_env_backend_spec as get_env_backend_spec
from synora.api import get_model_spec as get_model_spec
from synora.api import list_env_backends as list_env_backends
from synora.api import list_envs as list_envs
from synora.api import list_models as list_models
from synora.api import make_env as make_env
from synora.blocks.mhsa import MultiHeadSelfAttention as MultiHeadAttention
from synora.blocks.mhsa import MultiHeadSelfAttention as MultiHeadSelfAttention
from synora.blocks.st_transformer import STKVCache as STKVCache
from synora.blocks.st_transformer import STTransformer as STTransformer
from synora.configs.diamond_config import ATARI_100K_GAMES as ATARI_100K_GAMES
from synora.configs.diamond_config import DiamondConfig as DiamondConfig
from synora.configs.diamond_config import HUMAN_SCORES as HUMAN_SCORES
from synora.configs.diamond_config import RANDOM_SCORES as RANDOM_SCORES
from synora.configs.dit_config import DiTConfig as DiTConfig
from synora.configs.dit_config import dit_preset_config as dit_preset_config
from synora.configs.dit_config import get_dit_config as get_dit_config
from synora.configs.dit_config import list_dit_presets as list_dit_presets
from synora.configs.dreamer_config import DreamerConfig as DreamerConfig
from synora.configs.genie_config import DynamicsModelConfig as DynamicsModelConfig
from synora.configs.genie_config import GenieConfig as GenieConfig
from synora.configs.genie_config import GenieSmallConfig as GenieSmallConfig
from synora.configs.genie_config import LatentActionModelConfig as LatentActionModelConfig
from synora.configs.genie_config import STTransformerConfig as STTransformerConfig
from synora.configs.genie_config import VideoTokenizerConfig as VideoTokenizerConfig
from synora.configs.iris_config import IRISConfig as IRISConfig
from synora.configs.jepa_config import JEPAConfig as JEPAConfig
from synora.controller.iris_policy import CNNFeatureExtractor as CNNFeatureExtractor
from synora.controller.iris_policy import IRISActor as IRISActor
from synora.controller.iris_policy import IRISCritic as IRISCritic
from synora.controller.iris_policy import IRISPolicy as IRISPolicy
from synora.controller.rollout_generator import RolloutGenerator as RolloutGenerator
from synora.controller.rssm_policy import RSSMPolicy as RSSMPolicy
from synora.envs.ale_atari_env import list_available_atari_envs as list_available_atari_envs
from synora.envs.ale_atari_env import make_atari_env as make_atari_env
from synora.envs.ale_atari_vector_env import make_atari_vector_env as make_atari_vector_env
from synora.envs.brax_env import BraxImageEnv as BraxImageEnv
from synora.envs.brax_env import make_brax_env as make_brax_env
from synora.envs.bsuite_env import BSuiteImageEnv as BSuiteImageEnv
from synora.envs.bsuite_env import list_available_bsuite_ids as list_available_bsuite_ids
from synora.envs.bsuite_env import make_bsuite_env as make_bsuite_env
from synora.envs.diamond_atari import make_diamond_atari_env as make_diamond_atari_env
from synora.envs.dmc import DeepMindControlEnv as DeepMindControlEnv
from synora.envs.dmlab import DMLAB_LEVELS as DMLAB_LEVELS
from synora.envs.dmlab import DMLabEnv as DMLabEnv
from synora.envs.dmlab import make_dmlab_env as make_dmlab_env
from synora.envs.gym_env import GymImageEnv as GymImageEnv
from synora.envs.gym_env import make_gym_env as make_gym_env
from synora.envs.mujoco_env import MuJoCoImageEnv as MuJoCoImageEnv
from synora.envs.mujoco_env import MuJoCoImageEnv as MujocoEnv
from synora.envs.mujoco_env import make_mujoco_env as make_mujoco_env
from synora.envs.mujoco_env import make_mujoco_env_from_config as make_mujoco_env_from_config
from synora.envs.robotics_env import list_gymnasium_robotics_envs as list_gymnasium_robotics_envs
from synora.envs.robotics_env import make_robotics_env as make_robotics_env
from synora.envs.robotics_env import register_gymnasium_robotics_envs as register_gymnasium_robotics_envs
from synora.envs.unity_env import UnityMLAgentsEnv as UnityMLAgentsEnv
from synora.envs.unity_env import make_unity_mlagents_env as make_unity_mlagents_env
from synora.envs.world_model_env import WorldModelEnv as WorldModelEnv
from synora.envs.world_model_env import make_world_model_env as make_world_model_env
from synora.envs.wrappers import ActionRepeat as ActionRepeat
from synora.envs.wrappers import NormalizeActions as NormalizeActions
from synora.envs.wrappers import ObsDict as ObsDict
from synora.envs.wrappers import OneHotAction as OneHotAction
from synora.envs.wrappers import RenderImage as RenderImage
from synora.envs.wrappers import ResizeImage as ResizeImage
from synora.envs.wrappers import RewardObs as RewardObs
from synora.envs.wrappers import SelectAction as SelectAction
from synora.envs.wrappers import TimeLimit as TimeLimit
from synora.export import ExportableAgentMixin as ExportableAgentMixin
from synora.export import export_any as export_any
from synora.export import export_model as export_model
from synora.export import load_exported as load_exported
from synora.export import verify_export as verify_export
from synora.inference.benchmark import benchmark_step as benchmark_step
from synora.inference.benchmark import rollout_drift as rollout_drift
from synora.inference.bundle import load_bundle as load_bundle
from synora.inference.bundle import save_bundle as save_bundle
from synora.inference.precision import inference_context as inference_context
from synora.inference.quantize import quantize_weights as quantize_weights
from synora.inference.runtime import InferenceModel as InferenceModel
from synora.inference.runtime import optimize_for_inference as optimize_for_inference
from synora.inference.steppers import DreamerStepModule as DreamerStepModule
from synora.inference.steppers import DreamerStepper as DreamerStepper
from synora.inference.steppers import IRISStepper as IRISStepper
from synora.inference.steppers import make_stepper as make_stepper
from synora.layers.ada_ln_norm import AdaLNNormalization as AdaLNNormalization
from synora.layers.rms_norm import RMSNorm as RMSNorm
from synora.memory.dreamer_memory import ReplayBuffer as ReplayBuffer
from synora.memory.iris_memory import IRISOnPolicyBuffer as IRISOnPolicyBuffer
from synora.memory.iris_memory import IRISReplayBuffer as IRISReplayBuffer
from synora.memory.planet_memory import Episode as Episode
from synora.memory.planet_memory import Memory as Memory
from synora.models.diffusion.DDPM import DDPM as DDPM
from synora.models.diffusion.DiT import DiT as DiT
from synora.models.diffusion.DiT import PatchEmbed as PatchEmbed
from synora.models.diffusion.DiT import PatchUnEmbed as PatchUnEmbed
from synora.models.diffusion.DiT import create_dit as create_dit
from synora.models.diffusion.DiT import sinusoidal_time_embedding as sinusoidal_time_embedding
from synora.models.diffusion.actor_critic import ActorCriticNetwork as ActorCriticNetwork
from synora.models.diffusion.reward_termination import RewardTerminationModel as RewardTerminationModel
from synora.models.dreamer import Dreamer as Dreamer
from synora.models.dreamer import DreamerAgent as DreamerAgent
from synora.models.dreamer import preprocess_obs as preprocess_obs
from synora.models.dreamer_rssm import RSSM as DreamerRSSM
from synora.models.dreamer_rssm import RSSM as RSSM
from synora.models.dreamer_v1 import DreamerV1 as DreamerV1
from synora.models.dreamer_v1 import DreamerV1Agent as DreamerV1Agent
from synora.models.dreamer_v2 import DreamerV2 as DreamerV2
from synora.models.dreamer_v2 import DreamerV2Agent as DreamerV2Agent
from synora.models.dynamics_model import DynamicsModel as DynamicsModel
from synora.models.dynamics_model import create_dynamics_model as create_dynamics_model
from synora.models.genie import Genie as Genie
from synora.models.genie import create_genie as create_genie
from synora.models.genie import create_genie_large as create_genie_large
from synora.models.genie import create_genie_small as create_genie_small
from synora.models.iris_agent import IRISAgent as IRISAgent
from synora.models.iris_agent import compute_lambda_return as compute_lambda_return
from synora.models.iris_transformer import IRISTransformer as IRISTransformer
from synora.models.iris_transformer import IRISWorldModel as IRISWorldModel
from synora.models.jepa_agent import JEPAAgent as JEPAAgent
from synora.models.latent_action_model import LatentActionModel as LatentActionModel
from synora.models.latent_action_model import create_latent_action_model as create_latent_action_model
from synora.models.modular_rssm import ModularRSSM as ModularRSSM
from synora.models.modular_rssm import create_modular_rssm as create_modular_rssm
from synora.models.planet import Planet as Planet
from synora.models.rssm import RecurrentStateSpaceModel as RecurrentStateSpaceModel
from synora.models.vit import VisionTransformer as VisionTransformer
from synora.registry import deregister_env_backend as deregister_env_backend
from synora.registry import deregister_world_model as deregister_world_model
from synora.registry import get_registered_model_spec as get_registered_model_spec
from synora.registry import list_registered_env_backends as list_registered_env_backends
from synora.registry import list_registered_models as list_registered_models
from synora.registry import register_env_backend as register_env_backend
from synora.registry import register_world_model as register_world_model
from synora.reward.dreamer_v1_reward import RewardModel as DreamerRewardModel
from synora.reward.dreamer_v1_reward import RewardModel as RewardModel
from synora.reward.dreamer_v1_value import ValueModel as DreamerValueModel
from synora.reward.dreamer_v1_value import ValueModel as ValueModel
from synora.training.eval_jepa import jepa_linear_probe as jepa_linear_probe
from synora.training.eval_jepa import load_jepa_encoder as load_jepa_encoder
from synora.utils.deprecation import deprecated as deprecated
from synora.utils.deprecation import deprecated_class as deprecated_class
from synora.utils.deprecation import deprecated_function as deprecated_function
from synora.utils.dreamer_utils import FreezeParameters as FreezeParameters
from synora.utils.dreamer_utils import Logger as Logger
from synora.utils.dreamer_utils import compute_return as compute_return
from synora.utils.memory_utils import enable_performance_defaults as enable_performance_defaults
from synora.utils.memory_utils import maybe_compile as maybe_compile
from synora.utils.memory_utils import to_channels_last as to_channels_last
from synora.utils.throughput import ThroughputMeter as ThroughputMeter
from synora.utils.throughput import measure_steps as measure_steps
from synora.utils.throughput import tensor_nbytes as tensor_nbytes
from synora.vision.dreamer_decoder import ActionDecoder as ActionDecoder
from synora.vision.dreamer_decoder import ConvDecoder as ConvDecoder
from synora.vision.dreamer_decoder import DenseDecoder as DenseDecoder
from synora.vision.dreamer_decoder import SampleDist as SampleDist
from synora.vision.dreamer_decoder import TanhBijector as TanhBijector
from synora.vision.dreamer_encoder import ConvEncoder as ConvEncoder
from synora.vision.iris_decoder import IRISDecoder as IRISDecoder
from synora.vision.iris_encoder import IRISEncoder as IRISEncoder
from synora.vision.perceptual_loss import LPIPSPerceptualLoss as LPIPSPerceptualLoss
from synora.vision.perceptual_loss import build_perceptual_loss as build_perceptual_loss
from synora.vision.planet_decoder import CNNDecoder as CNNDecoder
from synora.vision.planet_encoder import CNNEncoder as CNNEncoder
from synora.vision.video_tokenizer import VideoTokenizer as VideoTokenizer
from synora.vision.video_tokenizer import create_video_tokenizer as create_video_tokenizer
from synora.vision.vq_layer import VectorQuantizer as VectorQuantizer
from synora.vision.vq_layer import VectorQuantizerEMA as VectorQuantizerEMA

__version__: str

def __getattr__(name: str) -> Any: ...


__all__ = [
    "ATARI_100K_GAMES",
    "ActionDecoder",
    "ActionRepeat",
    "ActorCriticNetwork",
    "AdaLNNormalization",
    "BSuiteImageEnv",
    "BraxImageEnv",
    "CNNDecoder",
    "CNNEncoder",
    "CNNFeatureExtractor",
    "ConvDecoder",
    "ConvEncoder",
    "DDPM",
    "DMLAB_LEVELS",
    "DMLabEnv",
    "DeepMindControlEnv",
    "DenseDecoder",
    "DiT",
    "DiTConfig",
    "DiamondConfig",
    "Dreamer",
    "DreamerAgent",
    "DreamerConfig",
    "DreamerRSSM",
    "DreamerRewardModel",
    "DreamerStepModule",
    "DreamerStepper",
    "DreamerV1",
    "DreamerV1Agent",
    "DreamerV2",
    "DreamerV2Agent",
    "DreamerValueModel",
    "DynamicsModel",
    "DynamicsModelConfig",
    "ENV_BACKEND_SPECS",
    "EnvBackendSpec",
    "Episode",
    "ExportableAgentMixin",
    "FreezeParameters",
    "Genie",
    "GenieConfig",
    "GenieSmallConfig",
    "GymImageEnv",
    "HUMAN_SCORES",
    "IRISActor",
    "IRISAgent",
    "IRISConfig",
    "IRISCritic",
    "IRISDecoder",
    "IRISEncoder",
    "IRISOnPolicyBuffer",
    "IRISPolicy",
    "IRISReplayBuffer",
    "IRISStepper",
    "IRISTransformer",
    "IRISWorldModel",
    "InferenceModel",
    "JEPAAgent",
    "JEPAConfig",
    "LPIPSPerceptualLoss",
    "LatentActionModel",
    "LatentActionModelConfig",
    "Logger",
    "MODEL_SPECS",
    "Memory",
    "ModelSpec",
    "ModularRSSM",
    "MuJoCoImageEnv",
    "MujocoEnv",
    "MultiHeadAttention",
    "MultiHeadSelfAttention",
    "NormalizeActions",
    "ObsDict",
    "OneHotAction",
    "PatchEmbed",
    "PatchUnEmbed",
    "Planet",
    "RANDOM_SCORES",
    "RMSNorm",
    "RSSM",
    "RSSMPolicy",
    "RecurrentStateSpaceModel",
    "RenderImage",
    "ReplayBuffer",
    "ResizeImage",
    "RewardModel",
    "RewardObs",
    "RewardTerminationModel",
    "RolloutGenerator",
    "STKVCache",
    "STTransformer",
    "STTransformerConfig",
    "SampleDist",
    "SelectAction",
    "TanhBijector",
    "ThroughputMeter",
    "TimeLimit",
    "UnityMLAgentsEnv",
    "ValueModel",
    "VectorQuantizer",
    "VectorQuantizerEMA",
    "VideoTokenizer",
    "VideoTokenizerConfig",
    "VisionTransformer",
    "WorldModelEnv",
    "__version__",
    "api",
    "benchmark_step",
    "build_perceptual_loss",
    "compute_lambda_return",
    "compute_return",
    "create_config",
    "create_dit",
    "create_dynamics_model",
    "create_genie",
    "create_genie_large",
    "create_genie_small",
    "create_latent_action_model",
    "create_model",
    "create_modular_rssm",
    "create_video_tokenizer",
    "deprecated",
    "deprecated_class",
    "deprecated_function",
    "deregister_env_backend",
    "deregister_world_model",
    "dit_preset_config",
    "enable_performance_defaults",
    "export_any",
    "export_model",
    "get_dit_config",
    "get_env_backend_spec",
    "get_model_spec",
    "get_registered_model_spec",
    "inference_context",
    "jepa_linear_probe",
    "list_available_atari_envs",
    "list_available_bsuite_ids",
    "list_dit_presets",
    "list_env_backends",
    "list_envs",
    "list_gymnasium_robotics_envs",
    "list_models",
    "list_registered_env_backends",
    "list_registered_models",
    "load_bundle",
    "load_exported",
    "load_jepa_encoder",
    "make_atari_env",
    "make_atari_vector_env",
    "make_brax_env",
    "make_bsuite_env",
    "make_diamond_atari_env",
    "make_dmlab_env",
    "make_env",
    "make_gym_env",
    "make_mujoco_env",
    "make_mujoco_env_from_config",
    "make_robotics_env",
    "make_stepper",
    "make_unity_mlagents_env",
    "make_world_model_env",
    "maybe_compile",
    "measure_steps",
    "optimize_for_inference",
    "preprocess_obs",
    "quantize_weights",
    "register_env_backend",
    "register_gymnasium_robotics_envs",
    "register_world_model",
    "rollout_drift",
    "save_bundle",
    "sinusoidal_time_embedding",
    "tensor_nbytes",
    "to_channels_last",
    "verify_export",
]
